{
    "name": "Delivery Date Scheduler",
    "version": "14.0",
    "depends": ['product', 'sale_management', 'delivery', 'base', 'stock', 'sale_stock', 'website', 'website_sale'],
    "author": "Redian Software",
    'currency': 'USD',
    'price': '27.0',
    "description": """Website Delivery Date Management""",
    "website": "https://www.rediansoftware.com/",
    "category": "Website Delivery Date Management ",
    "sequence": -108,
    'summary': 'It handle the delivery date created by customer on website',
    "demo": [],
    "data": [
        'security/ir.model.access.csv',
        'views/del_date_sale_view.xml',
        'views/res_config_settings_view.xml',
        'views/delivery_setting_view.xml',
        'views/delivery_date_template.xml',
    ],
    'auto_install': False,
    "installable": True,
    'application': True,
}
